### PR TITLE
Refactor the folder structure to have seperate folder for track 1 & track 2 samples

### PR DESCRIPTION
**Pull request by tadelesh**
Resolve https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/340

### CODE REVIEW

**Review by jhendrixMSFT — APPROVED** [review]
Looks great.  Is the POR to fix up CI separately?

**Comment by tadelesh** [comment]
> Looks great. Is the POR to fix up CI separately?

I've added a build and analyze pipeline for all the modules.

**Pull request merged**
