### PR TITLE
rename cosmos -> cosmosdb

### LINKED ISSUE #121: rename cosmos -> cosmosdb
cc @kanshiG

### PR DESCRIPTION
**Pull request by joshgav**
fixes #121

### CODE REVIEW

**Comment by mcardosos** [comment]
Maybe you also need to rename packages inside files

**Comment by vladbarosan** [comment]
@joshgav  there seems to be a conflict with cosmos_test.go

**Comment by vladbarosan** [comment]
@joshgav  also make sure to update the package name to match the folder name

**Comment by joshgav** [comment]
fixed! @vladbarosan can you review again? thanks.

**Pull request merged**
