### PR TITLE
Fixes CI to test if code can actually compile

### PR DESCRIPTION
**Pull request by mcardosos**
Thanks for your contribution! Please let us know what problems this PR addresses or what functionality it adds. Please link to other related issues and PRs to speed up review. Thank you!

### CODE REVIEW

**Comment by mcardosos** [comment]
Looks like dep using go 1.9 is somewhat recent
https://github.com/golang/dep#dep

**Comment by mcardosos** [comment]
Yes, changed 10 days ago
https://github.com/golang/dep/commit/52e5aba6a8039d99965e6cbcc6014c47aa382b9b

**Comment by vladbarosan** [comment]
@mcardosos  yes to build dep you need 1.9. but we should curl the dep binary isntead of building it ourselfs. Opened an issue here #134

So we are all good here. now it actually tests what is supposed to test ?

**Comment by mcardosos** [comment]
It tests :) merging

**Pull request merged**
